apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ping-deployment.yaml
- backendconfig.yaml
- statefulset.yaml
images:
- name: gcr.io/dwk-gke-450416/pingpong
  newName: gcr.io/dwk-gke-450416/pingpong
  newTag: main-a239c36f6b4bcb80d9c9a99fdfe951790abdad3b
