apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ping-deployment.yaml
  - backendconfig.yaml
images:
- name: gcr.io/dwk-gke-450416/pingpong
  newName: gcr.io/dwk-gke-450416/pingpong

